# Generated by Django 2.2.4 on 2021-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20210831_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service2',
            field=models.ManyToManyField(related_name='type', to='accounts_app.Service'),
        ),
    ]
