# Generated by Django 2.2.4 on 2021-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_appointment_service2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service2',
            field=models.ManyToManyField(to='accounts_app.Service'),
        ),
    ]
