# Generated by Django 2.2.4 on 2021-09-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20210928_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service2',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
