# Generated by Django 2.2.4 on 2021-10-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20210930_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='daycare_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='daycare_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
