# Generated by Django 2.2.4 on 2021-10-25 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_auto_20211015_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='daycare_end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='daycare_start_time',
        ),
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaltype', to='accounts_app.AnimalType')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
