# Generated by Django 2.2.4 on 2021-10-25 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_auto_20211025_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
