# Generated by Django 2.2.4 on 2021-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_daycare_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='daycare',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
